name: 'Continuous Integration'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    
    # Make sure go is installed
    - uses: actions/setup-go@v2
    - run: go version

    - uses: actions/cache@v2
      id: cache
      with:
        path: '**/function.zip.'
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    
    # Terraform expects the zip files to be created for each Lambda function
    # so we make sure the build happens first.
    - name: Run Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: make build

    # Setup AWS Creds
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=iac init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform -chdir=iac fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=iac plan -out plan.tfplan

    - name: "Terraform show"
      id: show
      run: terraform -chdir=iac show -json plan.tfplan > plan.json
      
    - uses: actions/upload-artifact@v2
      with:
        name: plan.json
        path: ./plan.json

    - name: Run infracost diff
      uses: infracost/infracost-gh-action@v0.7.0
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: ./plan.json

      # On push to master, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform -chdir=iac apply -auto-approve